---
title: "Seaweeds"
author: "Lilith Diener"
date: "2025-03-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 

Firstly, we install and load all necessary packages

```{r}

# Install packages
install.packages("ggmap")
install.packages("ggmap", dependencies = TRUE)
install.packages("ggspatial")
install.packages("osmdata")
install.packages("wesanderson") 


# Load packages
library(sf)
library(tidyverse)
library(ggplot2)
library(rinat)
library(rosm)
library(ggspatial)
library(ggmap)
library(osmdata)
library(leaflet)
library(htmltools)
library(mapview)
library(leafpop)
library(wesanderson)
library(dplyr)
```

```{r}
# Read in the Marine Protected Areas dataset
mpa <- st_read("C:\\Users\\Win10\\Documents\\GIT\\Gracilaria\\Gracilaria\\data\\SAMPAZ_OR_2024_Q3.shp")
 
# Check the CRS
st_crs(mpa)

class(mpa)
head (mpa)

# Write data with sf
 st_write(mpa, "C:\\Users\\Win10\\Documents\\GIT\\Gracilaria\\Gracilaria\\data\\SAMPAZ_OR_2024_Q3_duplicate.shp", append = FALSE)
 
file.exists("C:\\Users\\Win10\\Documents\\GIT\\Gracilaria\\Gracilaria\\data\\SAMPAZ_OR_2024_Q3_duplicate.shp")
```

```{r}
# Plot all (all columns, all of SA)
plot(mpa)

# Plot only column 2 from attribute table, all of SA
 plot(mpa[2])

# Plot using tidyverse
ggplot() + geom_sf(data=mpa, aes(fill = `CUR_NME`))
```

```{r}
 # Define bounding box for the Cape Peninsula
xmin <- 18.0   # Extend west to include Robben Island
xmax <- 19.2   # Extend east to include parts of False Bay
ymin <- -34.6  # Extend south to cover more of False Bay
ymax <- -33.7  # Extend north to include Robben Island

# Create a bounding box with the same CRS as the MPA data
cape_bbox <- st_bbox(c(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), crs = st_crs(mpa))
 
# Crop the MPA data to the Cape Peninsula region
mpa_cape <- st_crop(mpa, cape_bbox)

# Plot only cropped section of Cape Peninsula
plot(st_geometry(mpa_cape), col = 'lightblue', main = "Marine Protected Areas - Cape Peninsula")

#EVTL WEGLASSEN WEIL LABELS SICH ÜBERSCHNEIDEN
# Add MPA names as labels
text(st_coordinates(st_centroid(mpa_cape)), labels = mpa_cape$CUR_NME, cex = 0.8, col = "black", pos = 4)

# Use ggplot for better visualisation
# Convert to data frame for ggplot2
mpa_cape_df <- as.data.frame(st_coordinates(st_centroid(mpa_cape)))  # Get centroids
mpa_cape_df$CUR_NME <- mpa_cape$CUR_NME  # Add names
# Plot with ggplot2
ggplot() +
  geom_sf(data = mpa_cape, fill = "lightblue", color = "darkblue") +
  geom_text(data = mpa_cape_df, aes(X, Y, label = CUR_NME), size = 3, color = "black") +
  ggtitle("Marine Protected Areas - Cape Peninsula") +
  theme_minimal()

# Create a plot using ggplot2 with a legend 

# Convert MPA data to a data frame for ggplot2
mpa_cape$MPA_Name <- as.factor(mpa_cape$CUR_NME)  # Convert MPAs to factor values

# Plot with ggplot2
ggplot() +
  geom_sf(data = mpa_cape, aes(fill = CUR_NME), color = "black") +  
  scale_fill_viridis_d(name = "MPA Name") +  
  ggtitle("Marine Protected Areas - Cape Peninsula") +
  theme_minimal() +
  theme(legend.position = "right")  

# Remove boundaries within MPAs
mpa_cape %>% group_by(CUR_NME) %>% 
  summarize() %>% 
  ggplot() + geom_sf(aes(fill = CUR_NME))
```

```{r}
# Call species occurrence data from iNaturalist

# Ecklonia maxima
em <- get_inat_obs(taxon_name = "Ecklonia maxima",
                   bounds = c(-34.6, 18.0, -33.7, 19.2),
                   maxresults = 1000)

# View the first few rows of data
head(em)

# Gelidium pristoides
gpr <- get_inat_obs(taxon_name = "Gelidium pristoides",
                   bounds = c(-34.6, 18.0, -33.7, 19.2),
                   maxresults = 1000)

#View the first few rows of data
head(gpr)

# Laminaria pallida
lp <- get_inat_obs(taxon_name = "Laminaria pallida",
                   bounds = c(-34.6, 18.0, -33.7, 19.2),
                   maxresults = 1000)

# View the first few rows of data
head(lp)

# Merge the 3 datasets into a single data frame 
algae_data <- rbind(gpr, em, lp)

# Check structure
str(algae_data)

# Filter returned observations by a range of column attribute criteria
algae_data <- algae_data %>% filter(positional_accuracy<46 & 
                latitude<0 &
                !is.na(latitude) &
                captive_cultivated == "false" &
                quality_grade == "research")

class(algae_data) # check class

# Make the dataframe a spatial object of class = "sf"
algae_data <- st_as_sf(algae_data, coords = c("longitude", "latitude"), crs = 4326)

class(algae_data) # confirm new classes

# Note the new "geometry" column
names(algae_data)
```

```{r}
# ZU SEHR REINGEZOOMT, NICHT SELBER EXTENT WIE MPA MAP
# Plot 3 seaweed species
ggplot() + geom_sf(data=algae_data)

# Plot 3 seaweed species with MPAs and legend

ggplot() +
  # MPAs with different colors & legend
  geom_sf(data = mpa_cape, aes(fill = CUR_NME), color = "black", alpha = 0.5) +
  
  # Species occurrence points with legend
  geom_sf(data = algae_data, aes(color = scientific_name), size = 2) +
  
  # Color scales for MPAs and species
  scale_fill_viridis_d(name = "Marine Protected Areas") +  # MPA colors
  scale_color_manual(name = "Seaweed Species", values = c("red", "green", "blue", "purple")) +  # Species colors
  
  # Keep the correct map extent
  coord_sf(xlim = c(18.0, 19.2), ylim = c(-34.6, -33.7)) +
  
  # Title and theme
  ggtitle("MPAs and Algae Observations") +
  theme_minimal() +
  theme(legend.position = "right")  # Move legend to side
```

```{r}
# Make interactive map
leaflet() %>%
  # Add default OpenStreetMap map tiles
  addTiles(group = "Default") %>%  
  # Add our points
  addCircleMarkers(data = algae_data,
                   group = "Seaweeds",
                   radius = 3, 
                   color = "green") 

# Add popup labels to inspect data
mapview(algae_data, 
        popup = 
          popupTable(algae_data,
            zcol = c("scientific_name", "captive_cultivated", "url")))

# Make URLs links
l_algae_data <- algae_data %>%
  mutate(click_url = paste("<b><a href='", url, "'>Link to iNat observation</a></b>"))

mapview(algae_data, 
        popup = 
          popupTable(l_algae_data,
            zcol = c("scientific_name", "captive_cultivated", "click_url")))
```

```{r}
# Intersect species occurrences and MPAs
mpa_em_lp_gpr <- st_intersection(algae_data, mpa_cape)

# Confirm CRS of both datasets
st_crs(algae_data)
st_crs(mpa_cape)

# CRS do not match, so transform one dataset to match the other
algae_data <- st_transform(algae_data, st_crs(mpa_cape))


# Check dimensions before and after intersection
dim(algae_data) # before
algae_data <- st_intersection(algae_data, mpa_cape) # intersect
dim(algae_data) # after
```

```{r}
# Plot intersected dataset
ggplot() + 
  annotation_map_tile(type = "osm", progress = "none") + 
  geom_sf(data=algae_data)

# Colour points
pal <- wes_palette("Darjeeling1", 7, type = "continuous")

ggplot() + 
  annotation_map_tile(type = "osm", progress = "none") + 
  geom_sf(data=algae_data, aes(col = CUR_NME)) +
  scale_colour_manual(values = pal)

# Looks like almost all of them are in the Table Mountain National Park Marine
# Protected Area...
algae_data %>% group_by(CUR_NME) %>% summarise(n())

# That is correct. Note the numbers in column n(). But I can’t see where the 
# Betty's Bay (BB) MPA and Robben Island (RI) MPA records are, so let’s label these ' # with text # using geom_sf_label().
bb <- algae_data %>% filter(CUR_NME %in% c("Betty's Bay Marine Protected Area")) 
# find BB MPA localities

ri <- algae_data %>% filter(CUR_NME %in% c("Robben Island Marine Protected Area")) # find RI MPA localities

# Label Betty's Bay (BB) MPA and Robben Island (RI) MPA 
ggplot() + 
  annotation_map_tile(type = "osm", progress = "none") + 
  geom_sf(data = algae_data, aes(col = CUR_NME)) +
  scale_colour_manual(values = pal) +
  labs(color = "Marine Protected Areas") +  # Rename the legend title here
  geom_sf_label(data = bb %>% filter(CUR_NME == "Betty's Bay Marine Protected Area"), aes(label = "BB")) +
  geom_sf_label(data = ri %>% filter(CUR_NME == "Robben Island Marine Protected Area"), aes(label = "RI")) +
  theme_minimal()
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
